In [193]:
import numpy as np
import math

a = []
raw_A = []
b = []
x = []
Jb = []
c = []

def get_list_float_from_string(string):
    return [float(elem) for elem in string.split()]


with open('zlp.txt', 'r') as f:
    m, n = [int(elem) for elem in f.readline().split()]
    for _ in range(m):
        raw_A.append(get_list_float_from_string(f.readline()))
    A = array(raw_A)
    b = array(get_list_float_from_string(f.readline()))
    c = array(get_list_float_from_string(f.readline()))
    x = array(get_list_float_from_string(f.readline()))
    Jb = array(get_list_int_from_string(f.readline()))
        
print(A, "\nb = ", b, "\nc = ",  c, "\nx = ", x, "\nJb = ", Jb)

[[ 0.  1.  4.  1.  0. -8.  1.  5.]
 [ 0. -1.  0. -1.  0.  0.  0.  0.]
 [ 0.  2. -1.  0. -1.  3. -1.  0.]
 [ 1.  1.  1.  1.  0.  3.  1.  1.]] 
b =  [ 36. -11.  10.  20.] 
c =  [-5.  2.  3. -4. -6.  0.  1. -5.] 
x =  [4. 5. 0. 6. 0. 0. 0. 5.] 
Jb =  [1 2 4 8]


In [194]:
def simplex_main_phaze(c, a, b, x, j, m, n):
    i = 1
    j -= 1
    
    while True:
        A_t = a[:, j]
        B = np.linalg.inv(A_t)
        c_b = c[j]
        u = c_b @ B
        j_inv = delete(arange(n), j)
        delta = list(map(lambda inv: u @ a[:, inv] - c[inv], list(j_inv)))
        theta = []
        
        print("\nA: ", A_t, "\nB: ", B, "\nc_b: ", c_b, "\nВектор потенциалов: ", u, "\nВектор оценок: ", delta)
        
        j0 = j_inv[argmin(delta)]
        
        if is_optimal_solution(delta):
            print("\n\nРезультат: \nОптимальный план x0: ", list(map(lambda value: round(float(value), 4), list(x))), 
                  "\nc'x0: ", round(float(c @ x), 4), "\nКоличество итераций: ", i)
            return list(map(lambda value: round(float(value), 4), list(x))), round(float(c @ x), 4), i
            break
        
        z = B @ a[:, j0]
        print('z: ', z)
        
        if not all(value <= 0 for value in list(z)):
            print("Нет решений")
            break
                
        theta = [x[j[index]] / value if value > 0 else math.inf for index, value in enumerate(z)]
        index_min, theta_min = min(enumerate(theta), key=lambda pair: pair[1])
                
        s = index_min   
        print("s:", s + 1, "\njs: ", j[s] + 1)
        
        x[j_inv] = 0
        x[j0] = theta_min
        
        for index, value in zip(j, z):
            x[index] -= theta_min * value
            
        j[s] = j0
        print("Новый базисный план x: ", x, "\nНовый базис: ", j+1, "\n")
        i += 1
        
        
def is_optimal_solution(delta):
    for index, value in enumerate(delta):
        if value < 0:
            return False
    return True


simplex_main_phaze(c, A, b, x, Jb, m, n)


A:  [[ 0.  1.  1.  5.]
 [ 0. -1. -1.  0.]
 [ 0.  2.  0.  0.]
 [ 1.  1.  1.  1.]] 
B:  [[-0.2  0.8  0.   1. ]
 [ 0.   0.   0.5  0. ]
 [-0.  -1.  -0.5 -0. ]
 [ 0.2  0.2  0.   0. ]] 
c_b:  [-5.  2. -4. -5.] 
Вектор потенциалов:  [ 0. -1.  3. -5.] 
Вектор оценок:  [-11.0, 3.0, -6.0, -9.0]
z:  [ 0.2 -0.5  0.5  0.8]
s: 4 
js:  8
Новый базисный план x:  [2.75  8.125 6.25  2.875 0.    0.    0.    0.   ] 
Новый базис:  [1 2 4 3] 


A:  [[ 0.  1.  1.  4.]
 [ 0. -1. -1.  0.]
 [ 0.  2.  0. -1.]
 [ 1.  1.  1.  1.]] 
B:  [[-0.25   0.75   0.     1.   ]
 [ 0.125  0.125  0.5    0.   ]
 [-0.125 -1.125 -0.5   -0.   ]
 [ 0.25   0.25   0.     0.   ]] 
c_b:  [-5.  2. -4.  3.] 
Вектор потенциалов:  [ 2.75  1.75  3.   -5.  ] 
Вектор оценок:  [3.0, -28.0, -6.25, 13.75]
z:  [ 5.   0.5 -0.5 -2. ]
s: 1 
js:  1
Новый базисный план x:  [0.   7.85 7.35 3.15 0.   0.55 0.   0.  ] 
Новый базис:  [6 2 4 3] 


A:  [[-8.  1.  1.  4.]
 [ 0. -1. -1.  0.]
 [ 3.  2.  0. -1.]
 [ 3.  1.  1.  1.]] 
B:  [[-5.00000000e-02  1.5000

([0.0, 9.5, 5.3333, 1.5, 0.0, 0.0, 3.6667, 0.0], 32.6667, 4)